package cliente.presentacion;

import cliente.Cliente;
import cliente.utilidades.Parse;
import gestion_usuarios.dto.PacienteDTO;
import gestion_usuarios.utilidades.Utilidades;
import java.rmi.RemoteException;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import mvcf.AModel;
import mvcf.AView;

/**
 *
 * @author yerso
 */
public class GUIMenuSecretaria extends javax.swing.JFrame implements AView {

    /**
     * Creates new form GUIMenuAdmin
     */
    public GUIMenuSecretaria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gbtnTipoUsuarioReg = new javax.swing.ButtonGroup();
        tbpPrincipal = new javax.swing.JTabbedPane();
        pnlRegistrarPersonal = new javax.swing.JPanel();
        pnlTituloReg = new javax.swing.JPanel();
        lblTituloRegistrar = new javax.swing.JLabel();
        pnlIdReg = new javax.swing.JPanel();
        lblIdReg = new javax.swing.JLabel();
        txtIdReg = new javax.swing.JTextField();
        pnlNombreReg = new javax.swing.JPanel();
        lblNombreReg = new javax.swing.JLabel();
        txtNombreReg = new javax.swing.JTextField();
        pnlFacultadReg = new javax.swing.JPanel();
        pnlTipoIdRegIzq = new javax.swing.JPanel();
        lblTipoId = new javax.swing.JLabel();
        pnlTipoIdRegDere = new javax.swing.JPanel();
        txtFacultadReg = new javax.swing.JTextField();
        pnlOcupacionReg = new javax.swing.JPanel();
        pnlOcupacionRegIzq = new javax.swing.JPanel();
        lblTipoUsuarioReg = new javax.swing.JLabel();
        pnlOcupacionRegDere = new javax.swing.JPanel();
        rbtnDocenteReg = new javax.swing.JRadioButton();
        rbtnAdministrativoReg = new javax.swing.JRadioButton();
        pnlPatologiaReg = new javax.swing.JPanel();
        lblPatologiaReg = new javax.swing.JLabel();
        txtPatologiaReg = new javax.swing.JTextField();
        pnlUsuarioReg = new javax.swing.JPanel();
        lblUsuarioReg = new javax.swing.JLabel();
        txtUsuarioReg = new javax.swing.JTextField();
        pnlClave = new javax.swing.JPanel();
        lblClaveReg = new javax.swing.JLabel();
        pssClaveReg = new javax.swing.JPasswordField();
        pnlBotonRegistrar = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JButton();
        lblMensajeErrorReg = new javax.swing.JLabel();
        pnlModificarPersonal = new javax.swing.JPanel();
        pnlEliminarPersonal = new javax.swing.JPanel();
        pnlConsultarPersonal = new javax.swing.JPanel();
        pnlTituloConsultar = new javax.swing.JPanel();
        lblTituloConsultar = new javax.swing.JLabel();
        pnlConsultaConsultar = new javax.swing.JPanel();
        lblConsultaConsultar = new javax.swing.JLabel();
        txtConsultaConsultar = new javax.swing.JTextField();
        pnlInformacionConsultar = new javax.swing.JPanel();
        lblNombreConsultar = new javax.swing.JLabel();
        lblNombreConsultaRes = new javax.swing.JLabel();
        lblOcupacionConsultar = new javax.swing.JLabel();
        lblTipoUsuarioConsultaRes = new javax.swing.JLabel();
        lblUsuarioConsulta = new javax.swing.JLabel();
        lblUsuarioConsultaRes = new javax.swing.JLabel();
        lblFacultadConsultar = new javax.swing.JLabel();
        lblFacultadConsultarRes = new javax.swing.JLabel();
        pnlSurConsultar = new javax.swing.JPanel();
        pnlMasInfoConsulta = new javax.swing.JPanel();
        lblPatologiaConsultar = new javax.swing.JLabel();
        lblPatologiaConsultarRes = new javax.swing.JLabel();
        lblFechaIngresoConsultar = new javax.swing.JLabel();
        lblFechaIngresoConsultarRes = new javax.swing.JLabel();
        pnlBotonConsultar = new javax.swing.JPanel();
        btnConsultar = new javax.swing.JButton();
        lblMensajeErrorConsultar = new javax.swing.JLabel();
        pnlListarPersonal = new javax.swing.JPanel();
        pnlNorteListar = new javax.swing.JPanel();
        lblTituloListar = new javax.swing.JLabel();
        btnListar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaPacientes = new javax.swing.JTable();
        lblMensajeErrorListar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        tbpPrincipal.setPreferredSize(new java.awt.Dimension(500, 700));

        pnlRegistrarPersonal.setLayout(new java.awt.GridLayout(9, 0));

        pnlTituloReg.setLayout(new java.awt.GridLayout(1, 0));

        lblTituloRegistrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloRegistrar.setText("Registrar Paciente");
        pnlTituloReg.add(lblTituloRegistrar);

        pnlRegistrarPersonal.add(pnlTituloReg);

        pnlIdReg.setLayout(new java.awt.GridLayout(1, 0));

        lblIdReg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIdReg.setText("Identificaión");
        pnlIdReg.add(lblIdReg);
        pnlIdReg.add(txtIdReg);

        pnlRegistrarPersonal.add(pnlIdReg);

        pnlNombreReg.setLayout(new java.awt.GridLayout(1, 0));

        lblNombreReg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreReg.setText("Nombre Completo");
        pnlNombreReg.add(lblNombreReg);
        pnlNombreReg.add(txtNombreReg);

        pnlRegistrarPersonal.add(pnlNombreReg);

        pnlFacultadReg.setLayout(new java.awt.GridLayout(1, 2));

        pnlTipoIdRegIzq.setLayout(new java.awt.GridLayout(1, 0));

        lblTipoId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTipoId.setText("Facultad");
        pnlTipoIdRegIzq.add(lblTipoId);

        pnlFacultadReg.add(pnlTipoIdRegIzq);

        pnlTipoIdRegDere.setLayout(new java.awt.GridLayout(1, 0));
        pnlTipoIdRegDere.add(txtFacultadReg);

        pnlFacultadReg.add(pnlTipoIdRegDere);

        pnlRegistrarPersonal.add(pnlFacultadReg);

        pnlOcupacionReg.setLayout(new java.awt.GridLayout(1, 0));

        pnlOcupacionRegIzq.setLayout(new java.awt.GridLayout(1, 0));

        lblTipoUsuarioReg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTipoUsuarioReg.setText("Tipo de Usuario");
        pnlOcupacionRegIzq.add(lblTipoUsuarioReg);

        pnlOcupacionReg.add(pnlOcupacionRegIzq);

        pnlOcupacionRegDere.setLayout(new java.awt.GridLayout(2, 0));

        gbtnTipoUsuarioReg.add(rbtnDocenteReg);
        rbtnDocenteReg.setSelected(true);
        rbtnDocenteReg.setText("Docente");
        pnlOcupacionRegDere.add(rbtnDocenteReg);

        gbtnTipoUsuarioReg.add(rbtnAdministrativoReg);
        rbtnAdministrativoReg.setText("Administrativo");
        pnlOcupacionRegDere.add(rbtnAdministrativoReg);

        pnlOcupacionReg.add(pnlOcupacionRegDere);

        pnlRegistrarPersonal.add(pnlOcupacionReg);

        pnlPatologiaReg.setLayout(new java.awt.GridLayout(1, 0));

        lblPatologiaReg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPatologiaReg.setText("Patologia del Usuario");
        pnlPatologiaReg.add(lblPatologiaReg);
        pnlPatologiaReg.add(txtPatologiaReg);

        pnlRegistrarPersonal.add(pnlPatologiaReg);

        pnlUsuarioReg.setLayout(new java.awt.GridLayout(1, 0));

        lblUsuarioReg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuarioReg.setText("Usuario");
        pnlUsuarioReg.add(lblUsuarioReg);
        pnlUsuarioReg.add(txtUsuarioReg);

        pnlRegistrarPersonal.add(pnlUsuarioReg);

        pnlClave.setLayout(new java.awt.GridLayout(1, 0));

        lblClaveReg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClaveReg.setText("Clave");
        pnlClave.add(lblClaveReg);
        pnlClave.add(pssClaveReg);

        pnlRegistrarPersonal.add(pnlClave);

        pnlBotonRegistrar.setLayout(new java.awt.GridLayout(2, 0));

        btnRegistrar.setText("Registrar");
        pnlBotonRegistrar.add(btnRegistrar);
        pnlBotonRegistrar.add(lblMensajeErrorReg);

        pnlRegistrarPersonal.add(pnlBotonRegistrar);

        tbpPrincipal.addTab("Registar", pnlRegistrarPersonal);

        javax.swing.GroupLayout pnlModificarPersonalLayout = new javax.swing.GroupLayout(pnlModificarPersonal);
        pnlModificarPersonal.setLayout(pnlModificarPersonalLayout);
        pnlModificarPersonalLayout.setHorizontalGroup(
            pnlModificarPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 696, Short.MAX_VALUE)
        );
        pnlModificarPersonalLayout.setVerticalGroup(
            pnlModificarPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        tbpPrincipal.addTab("Modificar", pnlModificarPersonal);

        javax.swing.GroupLayout pnlEliminarPersonalLayout = new javax.swing.GroupLayout(pnlEliminarPersonal);
        pnlEliminarPersonal.setLayout(pnlEliminarPersonalLayout);
        pnlEliminarPersonalLayout.setHorizontalGroup(
            pnlEliminarPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 696, Short.MAX_VALUE)
        );
        pnlEliminarPersonalLayout.setVerticalGroup(
            pnlEliminarPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        tbpPrincipal.addTab("Eliminar", pnlEliminarPersonal);

        pnlConsultarPersonal.setLayout(new java.awt.GridLayout(3, 0));

        pnlTituloConsultar.setLayout(new java.awt.GridLayout(2, 0));

        lblTituloConsultar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloConsultar.setText("Consultar Personal");
        pnlTituloConsultar.add(lblTituloConsultar);

        pnlConsultaConsultar.setLayout(new java.awt.GridLayout(2, 0));

        lblConsultaConsultar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConsultaConsultar.setText("Ingrese ID del paciente");
        pnlConsultaConsultar.add(lblConsultaConsultar);

        txtConsultaConsultar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pnlConsultaConsultar.add(txtConsultaConsultar);

        pnlTituloConsultar.add(pnlConsultaConsultar);

        pnlConsultarPersonal.add(pnlTituloConsultar);

        pnlInformacionConsultar.setLayout(new java.awt.GridLayout(4, 2));

        lblNombreConsultar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreConsultar.setText("Nombre Completo");
        pnlInformacionConsultar.add(lblNombreConsultar);

        lblNombreConsultaRes.setText("-");
        pnlInformacionConsultar.add(lblNombreConsultaRes);

        lblOcupacionConsultar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOcupacionConsultar.setText("Tipo de Usuario");
        pnlInformacionConsultar.add(lblOcupacionConsultar);

        lblTipoUsuarioConsultaRes.setText("-");
        pnlInformacionConsultar.add(lblTipoUsuarioConsultaRes);

        lblUsuarioConsulta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuarioConsulta.setText("Usuario");
        pnlInformacionConsultar.add(lblUsuarioConsulta);

        lblUsuarioConsultaRes.setText("-");
        pnlInformacionConsultar.add(lblUsuarioConsultaRes);

        lblFacultadConsultar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFacultadConsultar.setText("Facultad");
        pnlInformacionConsultar.add(lblFacultadConsultar);

        lblFacultadConsultarRes.setText("-");
        pnlInformacionConsultar.add(lblFacultadConsultarRes);

        pnlConsultarPersonal.add(pnlInformacionConsultar);

        pnlSurConsultar.setLayout(new java.awt.GridLayout(2, 0));

        pnlMasInfoConsulta.setLayout(new java.awt.GridLayout(2, 0));

        lblPatologiaConsultar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPatologiaConsultar.setText("Patologia del Usuario");
        pnlMasInfoConsulta.add(lblPatologiaConsultar);

        lblPatologiaConsultarRes.setText("-");
        pnlMasInfoConsulta.add(lblPatologiaConsultarRes);

        lblFechaIngresoConsultar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFechaIngresoConsultar.setText("Fecha de Ingreso");
        pnlMasInfoConsulta.add(lblFechaIngresoConsultar);

        lblFechaIngresoConsultarRes.setText("-");
        pnlMasInfoConsulta.add(lblFechaIngresoConsultarRes);

        pnlSurConsultar.add(pnlMasInfoConsulta);

        pnlBotonConsultar.setLayout(new java.awt.GridLayout(2, 0));

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        pnlBotonConsultar.add(btnConsultar);
        pnlBotonConsultar.add(lblMensajeErrorConsultar);

        pnlSurConsultar.add(pnlBotonConsultar);

        pnlConsultarPersonal.add(pnlSurConsultar);

        tbpPrincipal.addTab("Consultar", pnlConsultarPersonal);

        pnlListarPersonal.setLayout(new java.awt.BorderLayout());

        pnlNorteListar.setLayout(new java.awt.GridLayout(1, 0));

        lblTituloListar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloListar.setText("Listar Pacientes");
        pnlNorteListar.add(lblTituloListar);

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });
        pnlNorteListar.add(btnListar);

        pnlListarPersonal.add(pnlNorteListar, java.awt.BorderLayout.NORTH);

        tblListaPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre Completo", "Tipo de Usuario", "Facultad", "Usuario", "Patologia", "FechaIngreso"
            }
        ));
        jScrollPane1.setViewportView(tblListaPacientes);

        pnlListarPersonal.add(jScrollPane1, java.awt.BorderLayout.CENTER);
        pnlListarPersonal.add(lblMensajeErrorListar, java.awt.BorderLayout.SOUTH);

        tbpPrincipal.addTab("Listar", pnlListarPersonal);

        getContentPane().add(tbpPrincipal);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        PacienteDTO pacienteDTO = null;
        int id = Parse.StringToInt(txtConsultaConsultar.getText());
//        try {
//            pacienteDTO = cliente.getGestor().consultarPaciente(id);
//        } catch (RemoteException ex) {
//            lblMensajeErrorConsultar.setText("Error al consultar personal.");
//        }

        if (pacienteDTO != null) {
            lblMensajeErrorConsultar.setText("Personal encontrado.");
            lblNombreConsultaRes.setText(pacienteDTO.getNombre());
            lblTipoUsuarioConsultaRes.setText(pacienteDTO.getTipoUsuario());
            lblUsuarioConsultaRes.setText(pacienteDTO.getUsuario());
            lblPatologiaConsultarRes.setText(pacienteDTO.getPatologia());
            lblFacultadConsultarRes.setText(pacienteDTO.getFacultad());
            lblFechaIngresoConsultarRes.setText(pacienteDTO.getFechaIngreso());
        } else {
            lblMensajeErrorConsultar.setText("Personal no encontrado.");
            lblNombreConsultaRes.setText("-");
            lblTipoUsuarioConsultaRes.setText("-");
            lblUsuarioConsultaRes.setText("-");
            lblFacultadConsultarRes.setText("-");
            lblPatologiaConsultarRes.setText("-");
            lblFechaIngresoConsultarRes.setText("-");
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        List<PacienteDTO> pacientes = null;
        DefaultTableModel modelo = (DefaultTableModel) tblListaPacientes.getModel();
        Object fila[] = new Object[7];

//        try {
//            pacientes = this.cliente.getGestor().listarPaciente();
//        } catch (RemoteException ex) {
//            lblMensajeErrorListar.setText("Error al listar personal.");
//        }

        if (pacientes != null) {
            for (PacienteDTO paciente : pacientes) {
                fila[0] = paciente.getId();
                fila[1] = paciente.getNombre();
                fila[2] = paciente.getTipoUsuario();
                fila[3] = paciente.getFacultad();
                fila[4] = paciente.getUsuario();
                fila[5] = paciente.getPatologia();
                fila[6] = paciente.getFechaIngreso();
                modelo.addRow(fila);
            }
        }
    }//GEN-LAST:event_btnListarActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GUIMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GUIMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GUIMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GUIMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GUIMenuAdmin().setVisible(true);
//            }
//        });
//    }

    public JButton getBtnConsultar() {
        return btnConsultar;
    }

    public JButton getBtnListar() {
        return btnListar;
    }

    public JButton getBtnRegistrar() {
        return btnRegistrar;
    }
    
    public JTextField getTxtNombreReg() {    
        return txtNombreReg;
    }

    public JTextField getTxtIdReg() {
        return txtIdReg;
    }

    public JRadioButton getRbtnDocenteReg() {
        return rbtnDocenteReg;
    }

    public JRadioButton getRbtnAdministrativoReg() {
        return rbtnAdministrativoReg;
    }

    public JTextField getTxtUsuarioReg() {
        return txtUsuarioReg;
    }

    public JTextField getTxtConsultaConsultar() {
        return txtConsultaConsultar;
    }

    public JTextField getTxtFacultadReg() {
        return txtFacultadReg;
    }

    public JTextField getTxtPatologiaReg() {
        return txtPatologiaReg;
    }

    public JPasswordField getPssClaveReg() {
        return pssClaveReg;
    }

    public JLabel getLblMensajeErrorReg() {
        return lblMensajeErrorReg;
    }
// Variables
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.ButtonGroup gbtnTipoUsuarioReg;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblClaveReg;
    private javax.swing.JLabel lblConsultaConsultar;
    private javax.swing.JLabel lblFacultadConsultar;
    private javax.swing.JLabel lblFacultadConsultarRes;
    private javax.swing.JLabel lblFechaIngresoConsultar;
    private javax.swing.JLabel lblFechaIngresoConsultarRes;
    private javax.swing.JLabel lblIdReg;
    private javax.swing.JLabel lblMensajeErrorConsultar;
    private javax.swing.JLabel lblMensajeErrorListar;
    private javax.swing.JLabel lblMensajeErrorReg;
    private javax.swing.JLabel lblNombreConsultaRes;
    private javax.swing.JLabel lblNombreConsultar;
    private javax.swing.JLabel lblNombreReg;
    private javax.swing.JLabel lblOcupacionConsultar;
    private javax.swing.JLabel lblPatologiaConsultar;
    private javax.swing.JLabel lblPatologiaConsultarRes;
    private javax.swing.JLabel lblPatologiaReg;
    private javax.swing.JLabel lblTipoId;
    private javax.swing.JLabel lblTipoUsuarioConsultaRes;
    private javax.swing.JLabel lblTipoUsuarioReg;
    private javax.swing.JLabel lblTituloConsultar;
    private javax.swing.JLabel lblTituloListar;
    private javax.swing.JLabel lblTituloRegistrar;
    private javax.swing.JLabel lblUsuarioConsulta;
    private javax.swing.JLabel lblUsuarioConsultaRes;
    private javax.swing.JLabel lblUsuarioReg;
    private javax.swing.JPanel pnlBotonConsultar;
    private javax.swing.JPanel pnlBotonRegistrar;
    private javax.swing.JPanel pnlClave;
    private javax.swing.JPanel pnlConsultaConsultar;
    private javax.swing.JPanel pnlConsultarPersonal;
    private javax.swing.JPanel pnlEliminarPersonal;
    private javax.swing.JPanel pnlFacultadReg;
    private javax.swing.JPanel pnlIdReg;
    private javax.swing.JPanel pnlInformacionConsultar;
    private javax.swing.JPanel pnlListarPersonal;
    private javax.swing.JPanel pnlMasInfoConsulta;
    private javax.swing.JPanel pnlModificarPersonal;
    private javax.swing.JPanel pnlNombreReg;
    private javax.swing.JPanel pnlNorteListar;
    private javax.swing.JPanel pnlOcupacionReg;
    private javax.swing.JPanel pnlOcupacionRegDere;
    private javax.swing.JPanel pnlOcupacionRegIzq;
    private javax.swing.JPanel pnlPatologiaReg;
    private javax.swing.JPanel pnlRegistrarPersonal;
    private javax.swing.JPanel pnlSurConsultar;
    private javax.swing.JPanel pnlTipoIdRegDere;
    private javax.swing.JPanel pnlTipoIdRegIzq;
    private javax.swing.JPanel pnlTituloConsultar;
    private javax.swing.JPanel pnlTituloReg;
    private javax.swing.JPanel pnlUsuarioReg;
    private javax.swing.JPasswordField pssClaveReg;
    private javax.swing.JRadioButton rbtnAdministrativoReg;
    private javax.swing.JRadioButton rbtnDocenteReg;
    private javax.swing.JTable tblListaPacientes;
    private javax.swing.JTabbedPane tbpPrincipal;
    private javax.swing.JTextField txtConsultaConsultar;
    private javax.swing.JTextField txtFacultadReg;
    private javax.swing.JTextField txtIdReg;
    private javax.swing.JTextField txtNombreReg;
    private javax.swing.JTextField txtPatologiaReg;
    private javax.swing.JTextField txtUsuarioReg;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actualizar(AModel arg0) {
    }
}
