/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cliente.presentacion;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import mvcf.AModel;
import mvcf.AView;

/**
 *
 * @author juan sebastian
 */
public class GUIPaciente extends javax.swing.JFrame implements AView {

    /**
     * Creates new form GUIPaciente
     */
    public GUIPaciente() {
         initComponents();
         String []info = new String[3];
         this.tbl2ConsultarAsistencia.setValueAt("X", 2, 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbpPrincipal = new javax.swing.JTabbedPane();
        pnlConsultarP = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIdentificacionPlan = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblConsultarPlan = new javax.swing.JTable();
        pnlConsultarV = new javax.swing.JPanel();
        txtIdValoracion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnConsultarValoracion = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtValoracionRes = new javax.swing.JTextArea();
        pnlConsultarA = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt2Identificacion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl2ConsultarAsistencia = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Consultar plan fisico");

        jLabel2.setText("Identificación");

        tblConsultarPlan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", null, null, null, null, null, null, null, null, null},
                {"2", "", null, null, null, null, null, null, null, null},
                {"3", null, null, null, null, null, null, null, null, null},
                {"4", null, null, null, null, null, null, null, null, null},
                {"5", null, null, null, null, null, null, null, null, null},
                {"6", null, null, null, null, null, null, null, null, null},
                {"7", null, null, null, null, null, null, null, null, null},
                {"8", null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Semana", "Ejercicio1", "Cant", "Peso", "Ejercicio2", "Cant", "Peso", "Ejercicio3", "Cant", "Peso"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblConsultarPlan.setName(""); // NOI18N
        jScrollPane2.setViewportView(tblConsultarPlan);
        if (tblConsultarPlan.getColumnModel().getColumnCount() > 0) {
            tblConsultarPlan.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblConsultarPlan.getColumnModel().getColumn(2).setPreferredWidth(50);
            tblConsultarPlan.getColumnModel().getColumn(3).setPreferredWidth(50);
            tblConsultarPlan.getColumnModel().getColumn(5).setPreferredWidth(50);
            tblConsultarPlan.getColumnModel().getColumn(6).setPreferredWidth(50);
            tblConsultarPlan.getColumnModel().getColumn(8).setPreferredWidth(50);
            tblConsultarPlan.getColumnModel().getColumn(9).setPreferredWidth(50);
        }

        javax.swing.GroupLayout pnlConsultarPLayout = new javax.swing.GroupLayout(pnlConsultarP);
        pnlConsultarP.setLayout(pnlConsultarPLayout);
        pnlConsultarPLayout.setHorizontalGroup(
            pnlConsultarPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultarPLayout.createSequentialGroup()
                .addGroup(pnlConsultarPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlConsultarPLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtIdentificacionPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlConsultarPLayout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(jLabel1))
                    .addGroup(pnlConsultarPLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        pnlConsultarPLayout.setVerticalGroup(
            pnlConsultarPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultarPLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlConsultarPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdentificacionPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        tbpPrincipal.addTab("Plan fisico", pnlConsultarP);

        jLabel5.setText("Identificación");

        jLabel7.setText("Consultar Valoracion");

        btnConsultarValoracion.setText("Consultar Valoracion");

        txtValoracionRes.setEditable(false);
        txtValoracionRes.setColumns(20);
        txtValoracionRes.setRows(5);
        jScrollPane1.setViewportView(txtValoracionRes);

        javax.swing.GroupLayout pnlConsultarVLayout = new javax.swing.GroupLayout(pnlConsultarV);
        pnlConsultarV.setLayout(pnlConsultarVLayout);
        pnlConsultarVLayout.setHorizontalGroup(
            pnlConsultarVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultarVLayout.createSequentialGroup()
                .addGroup(pnlConsultarVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlConsultarVLayout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jLabel7))
                    .addGroup(pnlConsultarVLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(pnlConsultarVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnConsultarValoracion)
                            .addGroup(pnlConsultarVLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtIdValoracion, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        pnlConsultarVLayout.setVerticalGroup(
            pnlConsultarVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultarVLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(26, 26, 26)
                .addGroup(pnlConsultarVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtIdValoracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConsultarValoracion)
                .addGap(59, 59, 59))
        );

        tbpPrincipal.addTab("Valoracion", pnlConsultarV);

        jLabel3.setText("Identificación");

        jLabel4.setText("Consultar Asistencia");

        tbl2ConsultarAsistencia.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbl2ConsultarAsistencia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", null, null, null, null, null, null, null},
                {"2", "", null, null, null, null, null, null},
                {"3", null, null, null, null, null, null, null},
                {"4", null, "", null, null, null, null, null},
                {"5", null, null, null, null, null, null, null},
                {"6", null, null, null, null, null, null, null},
                {"7", null, null, null, null, null, null, null},
                {"8", null, null, null, null, null, null, null}
            },
            new String [] {
                "Semana", "Dia1", "Dia2", "Dia3", "Dia4", "Dia5", "Dia6", "Dia7"
            }
        ));
        tbl2ConsultarAsistencia.setName(""); // NOI18N
        jScrollPane3.setViewportView(tbl2ConsultarAsistencia);
        if (tbl2ConsultarAsistencia.getColumnModel().getColumnCount() > 0) {
            tbl2ConsultarAsistencia.getColumnModel().getColumn(0).setPreferredWidth(50);
            tbl2ConsultarAsistencia.getColumnModel().getColumn(2).setPreferredWidth(20);
            tbl2ConsultarAsistencia.getColumnModel().getColumn(3).setPreferredWidth(20);
            tbl2ConsultarAsistencia.getColumnModel().getColumn(4).setPreferredWidth(20);
            tbl2ConsultarAsistencia.getColumnModel().getColumn(5).setPreferredWidth(20);
            tbl2ConsultarAsistencia.getColumnModel().getColumn(6).setPreferredWidth(20);
            tbl2ConsultarAsistencia.getColumnModel().getColumn(7).setPreferredWidth(20);
        }

        javax.swing.GroupLayout pnlConsultarALayout = new javax.swing.GroupLayout(pnlConsultarA);
        pnlConsultarA.setLayout(pnlConsultarALayout);
        pnlConsultarALayout.setHorizontalGroup(
            pnlConsultarALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultarALayout.createSequentialGroup()
                .addGroup(pnlConsultarALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlConsultarALayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlConsultarALayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(pnlConsultarALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlConsultarALayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt2Identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4))))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        pnlConsultarALayout.setVerticalGroup(
            pnlConsultarALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultarALayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(pnlConsultarALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt2Identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tbpPrincipal.addTab("Asistencia", pnlConsultarA);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbpPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tbpPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GUIPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GUIPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GUIPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GUIPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GUIPaciente().setVisible(true);
//            }
//        });
//    }
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GUIPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GUIPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GUIPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GUIPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GUIPaciente().setVisible(true);
//            }
//        });
//    }
    public JButton getBtnConsultarValoracion() {
        return btnConsultarValoracion;
    }    

    public JTextArea getTxtValoracionRes() {
        return txtValoracionRes;
    }

    public JTextField getTxtIdValoracion() {
        return txtIdValoracion;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarValoracion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel pnlConsultarA;
    private javax.swing.JPanel pnlConsultarP;
    private javax.swing.JPanel pnlConsultarV;
    private javax.swing.JTable tbl2ConsultarAsistencia;
    private javax.swing.JTable tblConsultarPlan;
    private javax.swing.JTabbedPane tbpPrincipal;
    private javax.swing.JTextField txt2Identificacion;
    private javax.swing.JTextField txtIdValoracion;
    private javax.swing.JTextField txtIdentificacionPlan;
    private javax.swing.JTextArea txtValoracionRes;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actualizar(AModel arg0) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
